name: Build Rust SDK on latest C SDK

on:
  workflow_dispatch:
  pull_request:

jobs:
    test_build_rust:
        name: Build Rust SDK
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
        strategy:
            matrix:
                target: ["nanox", "nanosplus", "stax", "flex"]
        steps:
            - name: Clone C SDK
              uses: actions/checkout@v4
              with:
                path: c_sdk
            - name: Clone Rust SDK
              uses: actions/checkout@v4
              with:
                  repository: LedgerHQ/ledger-device-rust-sdk
                  ref: y333/update_swap_arg
                  path: rust_sdk
            - name: Build Rust SDK
              working-directory: rust_sdk/ledger_device_sdk
              run: |
                  export LEDGER_SDK_PATH=$GITHUB_WORKSPACE/c_sdk
                  cargo +$RUST_NIGHTLY build --target ${{ matrix.target }}
